const services = {
  EXAM_SERVICE: 'EXAM_SERVICE',
  SCHOOL_SERVICE: 'SCHOOL_SERVICE',
  USER_PROGRESS_SERVICE: 'USER_PROGRESS_SERVICE',
  COURSE_SERVICE: 'COURSE_SERVICE',
  SYNC_GATEWAY_SERVICE: 'SYNC_GATEWAY_SERVICE',
};

const programTypes = {
  MODULE_PROGRAM: 'MODULE_PROGRAM',
  WORKING_PROGRAM: 'WORKING_PROGRAM',
};

const allStatus = {
  PUBLISHED: 'PUBLISHED',
  ACTIVE: 'ACTIVE',
};

const entities = {
  COURSE: 'COURSE',
  MODULE: 'MODULE',
  MODULE_LESSON: 'MODULE_LESSON',
  LAST_UPDATE: 'LAST_UPDATE',
  SCHEDULE_GROUP: 'SCHEDULE_GROUP',
};

module.exports = {
  services,
  programTypes,
  allStatus,
  entities,
};
